name: Deploy job

on:
  push:
    branches:
      - master
    paths:
      - 'job/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: check code
        run: ls
      - name: Build Docker Image
        run: docker build -t nguyenhung1402/job  ./job
      - name: Publish Image to docker hub
        run: docker push nguyenhung1402/job 
      