name: Deploy job

on:
  push:
    branches:
      - master
    paths:
      - 'job/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Go to job
        run: cd job
      - name: Deploy
        run: echo "Deploying"
      