name: Deploy user

on:
  push:
    branches:
      - master
    paths:
      - 'user/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Go to user
        run: cd user
      - name: Deploy
        run: echo "Deploying"
      
