name: Deploy job

on:
  push:
    branches:
      - master
    paths:
      - 'job/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Go to job
        run: cd job
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}    
      - name: Build Docker Image
        run: docker build -t nguyenhung1402/job  .
      - name: Publish Image to docker hub
        run: docker push nguyenhung1402/job 
      