name: Test Job

on: 
  pull_request:
    paths:
    - 'job/**'


jobs:
  checkQuality:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: job
          args: >
              -Dsonar.organization=cuong199344
              -Dsonar.projectKey=cuong199344
              -Dsonar.python.coverage.reportPaths=coverage.xml